export const SET_GAME_STARTED = 'SET_GAME_STARTED';
export const EXPAND_INSTRUCTIONS = 'EXPAND_INSTRUCTIONS';
export const FETCH_DECK_RESULTS = 'FETCH_DECK_RESULTS';
export const FETCH_DECK_ERROR = 'FETCH_DECK_ERROR';
export const DRAW_CARD_RESULTS = 'DRAW_CARD_RESULTS';
export const DRAW_CARD_ERROR = 'DRAW_CARD_ERROR';
export const SET_GUESS = 'SET_GUESS';

export const GUESS = {
    ODD: 0,
    EVEN: 1
};
